{\rtf1\ansi\ansicpg1252\cocoartf2577
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 HelveticaNeue-Bold;\f1\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red251\green0\blue7;\red0\green0\blue0;\red0\green128\blue0;
}
{\*\expandedcolortbl;;\cssrgb\c100000\c0\c0;\cssrgb\c0\c0\c0\cname textColor;\csgenericrgb\c0\c50000\c0;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\li1400\fi-1400\partightenfactor0

\f0\b\fs26 \cf2 00:00:44
\f1\b0\fs24 \cf3 :  ERROR: Python execution failed: Traceback (most recent call last):\
  File "<string>", line 1, in <module>\
  File "/var/folders/y0/drlxvjc91n5702jcv_ylnz3h0000gp/T/MWorks/Experiment Cache/_Users_hansem_Documents_MazeSetGo_task_moog_human.mwel/tmp/task.py", line 68, in __init__\
    config_class = getattr(config_module, level_split[-1])(\
  File "/Users/hansem/Documents/MazeSetGo/task/configs/levels/random/random_12.py", line 12, in random_12\
    stimulus_generator = samplers.Sampler(\
  File "/Users/hansem/Documents/MazeSetGo/task/configs/samplers.py", line 34, in __init__\
    self._load_stimuli(stimuli_dir)\
  File "/Users/hansem/Documents/MazeSetGo/task/configs/samplers.py", line 63, in _load_stimuli\
    filter(lambda s: s.isnumeric(), os.listdir(stimuli_dir)))\
PermissionError: [Errno 13] Permission denied: '/Users/jazlab/Documents/MazeSetGo/task/stimuli/random/Random12Square'\
 [line 297, column 5]\

\f0\b\fs26 \cf4 00:00:44
\f1\b0\fs24 \cf3 :  ********    STARTING TASK    ******** (44225442)\

\f0\b\fs26 \cf4 00:00:44
\f1\b0\fs24 \cf3 :  ****  BEGINNING TRIAL  0 **** (44225517)\

\f0\b\fs26 \cf2 00:00:44
\f1\b0\fs24 \cf3 :  ERROR: Python execution failed: Traceback (most recent call last):\
  File "<string>", line 1, in <module>\
NameError: name 't' is not defined\
 [line 141, column 17; via line 299, column 5]\
}